name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10   # ✅ FIXED

    - name: Install Dependencies
      run: |
        pip install flask
        pip install selenium

    - name: Run Unit Tests
      run: |
        python -m unittest discover tests